apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: esddns-operator
  namespace: esddns-system
  labels:
    app: esddns
spec:
  selector:
    matchLabels:
      app: esddns-operator
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: esddns-service
  namespace: esddns-system
  labels:
    app: esddns
spec:
  selector:
    matchLabels:
      app: esddns-service
  endpoints:
  - port: web
    interval: 30s
    path: /metrics
