apiVersion: v1
kind: Secret
metadata:
  name: esddns-gandi-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "esddns-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.gandi.apiKey | quote }}
