{{- if .Values.monitoring.enabled }}
{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: esddns-operator
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "esddns-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "esddns-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: esddns-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "esddns-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "esddns-operator.selectorLabels" . | nindent 6 }}
      app: esddns-service
  endpoints:
  - port: web
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
    path: /metrics
{{- end }}
{{- end }}
