{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: esddns-operator
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "esddns-operator.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: esddns-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "esddns-operator.labels" . | nindent 4 }}
{{- end }}
