apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - appproject.yaml
  - applications/

commonLabels:
  environment: production
  app.kubernetes.io/name: esddns
  app.kubernetes.io/component: argocd-applications
