apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: esddns-system

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemon-deployment.yaml
  - service-deployment.yaml
  - service.yaml
  - secrets.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: esddns
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/part-of: esddns

commonAnnotations:
  app.kubernetes.io/documentation: "https://github.com/sqe/esddns"
